name: Health Check

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Check the deployed service URL
              uses: jtalk/url-health-check-action@v1.5
              with:
                  url: https://kirill-fullstack-p7-deploy.herokuapp.com/health
                  follow-redirect: no
                  max-attempts: 3
                  retry-delay: 15s
                  retry-all: no
